[package]
name = "opaque-vpn"
version = "0.0.1"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
tokio = { version = "1.42.0", features = ["net", "rt"] }
tokio-rustls = "0.26.1"
yaml-rust = "0.4.5"
