[client]
address = "madprogrammer.net"
port = 10001
[tls]
root_certificate = '''
-----BEGIN CERTIFICATE-----
MIIFvTCCA6WgAwIBAgIUJeJaPE/ZNdAFZFrEfovXxrts4RUwDQYJKoZIhvcNAQEL
BQAwbjELMAkGA1UEBhMCUlUxEzARBgNVBAgMClNvbWUtU3RhdGUxDzANBgNVBAcM
Bk1vc2NvdzEhMB8GA1UECgwYSW50ZXJuZXQgV2lkZ2l0cyBQdHkgTHRkMRYwFAYD
VQQDDA1NYWRQcm9ncmFtbWVyMB4XDTI0MTExNzIxMTc1MVoXDTM0MTExNTIxMTc1
MVowbjELMAkGA1UEBhMCUlUxEzARBgNVBAgMClNvbWUtU3RhdGUxDzANBgNVBAcM
Bk1vc2NvdzEhMB8GA1UECgwYSW50ZXJuZXQgV2lkZ2l0cyBQdHkgTHRkMRYwFAYD
VQQDDA1NYWRQcm9ncmFtbWVyMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKC
AgEAixTsZapnehieL3LDwMahAUZ/2lM0fCN4rwwVu57ZVm+k7QIRksw9dfwOb6tW
f6hTNM0BsKPCL+y2QNsI9Syv3Vy965u6JNULFt91FOvuQgJubJhJx+EBCJ0XhUed
qwNRqllHq0XyHjSUhdJ2kOGTEqomZ1cliZXL/XDnJooUFbqEF7/3l/oV6a5u4BeS
vJv8uRGVRDBb5JAg0rmrQJXhIWhGDhnq7D5wSvGChS/qiDfh4EktiU7JelR3shXc
32sZPXCReCENftdtABiYJSRGNQeVhuUVf3M9f6KxMr9kecrMsMUtJu+5EjEvxHM3
FWC+QqCoIHJRmZLFE4AO6uejSwc/zvsBGScav4D8fmVc4HmF9MHFVXCaQaKEu/jX
JexyFU6n6QS0BJoDPjKkYkT0sn2fa0p8wKtXc62J9b1G/dcdPvThjKkxmbxFsfoK
CyIw5xepSIRqY7izgdHVTQ7GdTY/c63JG91guYzlmk7LZa5kH3jHkF81ZnamRK6n
y2xVpfAP/arF3jYlUktPfDtVqoGaYYi3GKTsDYpZBfG+HxZCFT01Glp3P/MRcGcf
jN8ezeegilbXzT2U7W6vhZoMZMQOR17vO30clvPcjV9Kpgvz8maWqyPCzNONsIpb
YNjjppy7anU4fikZeOKTxsvqEATzllQd7hyiizT9MhIyie0CAwEAAaNTMFEwHQYD
VR0OBBYEFFc8M9var1OWIjiZBXZcJZHkN5VDMB8GA1UdIwQYMBaAFFc8M9var1OW
IjiZBXZcJZHkN5VDMA8GA1UdEwEB/wQFMAMBAf8wDQYJKoZIhvcNAQELBQADggIB
AHMaEZsO3ebO8LC/WevQtF0mzMyp45XDZt0GzY7CUNHlbqshVqgXfMBNsI8JBtJ7
iJm6ZJaOoJjezxo8eUY8qZKMJcm7OFSDC/1z4gNJKBTrXbc2SEd97HzIF5Tb5KEK
vlpxuTXULnMx+h09AkupiTpwWc/kn1/d0yE9hWLLJ3a5M02mhQiuEoUoig3SGNEP
/Df892gKkOVk+j3eKf/Ja1R8mRmAOxoAK1Y++S0eQO7dzGBrur6pzJyUjw31HPCh
/rOwxAqtArxkKnFEgVgprdNoV1KDYwk9QOG0AjmRstPK/4FR/E33sAaRQOIhV0RM
kxM/Vb/2kFBp3OaOpyxc4Grpua5CBdLAcERUgLbIdkWkSXjc/zVW3orGqYJW6T1M
9KGZmzv40B04v+8/IBPTjktlibMIdSeT6+Sp7Ogk7AguLZGhs3c0v5anWhfhfC0P
+Rzm5JUT7Mb4DITkxp8HbpxyGQQOkQoOKOLLogTm2H6B1i7ss+zgYnYbuwISs19a
2txCaIfDj2TR4GXB/ed6fV3K3OyIzYDjQNXwQkDfd/nz7986y0RvMTjObVENJVl8
6Dy17i/V+DqlWj+/dHzlHZmiYjc5yuGeJMU+pUiZrtLxWumkGIdZwDHWqbF3aanw
cv8uOVY3rE5aOPpmaMj6tTq06vLA+Ual8RlbhARFI4Ty
-----END CERTIFICATE-----
'''
certificate = '''
-----BEGIN CERTIFICATE-----
MIIFjzCCA3egAwIBAgIULKUUU1qV3dDeFJzbBQr6mWIgET0wDQYJKoZIhvcNAQEL
BQAwbjELMAkGA1UEBhMCUlUxEzARBgNVBAgMClNvbWUtU3RhdGUxDzANBgNVBAcM
Bk1vc2NvdzEhMB8GA1UECgwYSW50ZXJuZXQgV2lkZ2l0cyBQdHkgTHRkMRYwFAYD
VQQDDA1NYWRQcm9ncmFtbWVyMB4XDTI0MTIyNjE3NTUyMFoXDTI1MTIyNjE3NTUy
MFowUTELMAkGA1UEBhMCUlUxDzANBgNVBAgMBk1vc2NvdzEOMAwGA1UEBwwFTW9z
Y28xITAfBgNVBAoMGEludGVybmV0IFdpZGdpdHMgUHR5IEx0ZDCCAiIwDQYJKoZI
hvcNAQEBBQADggIPADCCAgoCggIBALn5+8gn10S6Apc0gFT8wn6AgkuSn6ysZBzY
1cEId56vFut7C0jpkODSOW2ez6KJNE4Wy6ZuRHunbyunlrRCll19XEd0xpBlCBCx
jY5Be5xvkqNtaFqqQnTD4gyWiU89TPjzpqf4KSw3Q8Q6K7+QBNOGXOUXgDitiLRv
ByqdlEuTHFBSKntI2wmxXI3RjVje6rTaNOV6edfNm/qsWhYvaitk50iqyUe/MG/h
PqgTjPqgrVqFGAECGLvMuB+ZdOrOZbxJf4MzEgs/9mLnVA9h7uCI5he2WyaxDBar
Ko8/Fd83w/4IWiBmpxFO7fQO0BiZf0xP64O7zaiM90r6TytPcvqIQaQ6RXo94gRw
iaWyTW+OAg3xxAI74x5qz+sP3B4SahgNzQoA8CrDolBLLO0R/Lj2vb+JD1WN0oEP
DH51DuUetL5bUUnwTa/I3hHqeAsy/MzQ1hjNm7/2/sRzttzO+1Enf+ZDiZAns9AQ
es2iVIGp6TnvuYwPxme1l/K92bDlMa3yKxbkzDTG3HLlbIjGbbE16cqMJ91r6m+p
V5zapW6PYOzYpqRD/JzWfCdSSMjjlzX6WW/92vowi0FYT18NbcXhtsV0VkX0D+on
i8lScYFPNKlZ9FXViyE8CwNjQcHVaxB7ELEfMRnERtbp8nQvfpVj/avKCWCRU08N
46ezCfHZAgMBAAGjQjBAMB0GA1UdDgQWBBTsdoCas7mABvWdh2hIlQr5fjd5izAf
BgNVHSMEGDAWgBRXPDPb2q9TliI4mQV2XCWR5DeVQzANBgkqhkiG9w0BAQsFAAOC
AgEACFS9DjIPw7SU0fe/KlART5lM28ZwjazAM7ASDRpAwV5/87QFYy9j3eCs454L
slgFzpCB2dDqMI+pF6lnEByFi5m7chfaZEaEbz2fxXnAww7NDyuZBr5KrMEd5eNy
Qvcs70gj8ruUQBq2Do4htvDXb3Xl1xjO+in36dRAktQpiuln+4MnaWnK9sFutiOR
E2i9d1HPZRlknWvCtCmNnVTGoZLGx0Q9rdhrQTaDdMk00dzKLmmLJSuqvSVVgJXX
Q3D2m4Oa9n8af/bl/cwdu0c7NWiDsSEReSLfzrwYrMDPBxrztFoSmWbx9t/cn5yC
FaMYN9TAvZj65VGg60+2z6J+2BFfMFQy6umgvqqZ6q/wkrypgRFQCf8zmdt34fN2
+97QEwez2oAmJyvX5Mx4USH8+epWN5YVKJhBUrtZ5e9cBT0flNLmFQ9d94y3Jfbk
ZIBx+luFSNBXgvW9v7uEiBDi8nviCt6wQAbuA5aTQMLAcMxyDiDHB9h8Ctx9usct
sCE2EGXZ1RzZhtRDaK8h5p0MF2P8jsSJ/PZHsRsns8yVmE5AADC0NCxETquDrcg1
b3iukN7v3KgE6lvvq+uE12thiJI/88qs2UVSw+vESmWCe02OyXbWXUupNifIuIsR
ufBeco+5w9Klco5/8kaiVXZym4MGXx7w/yFNWsXdOBNsDhk=
-----END CERTIFICATE-----
'''
key = '''
-----BEGIN PRIVATE KEY-----
MIIJQwIBADANBgkqhkiG9w0BAQEFAASCCS0wggkpAgEAAoICAQC5+fvIJ9dEugKX
NIBU/MJ+gIJLkp+srGQc2NXBCHeerxbrewtI6ZDg0jltns+iiTROFsumbkR7p28r
p5a0QpZdfVxHdMaQZQgQsY2OQXucb5KjbWhaqkJ0w+IMlolPPUz486an+CksN0PE
Oiu/kATThlzlF4A4rYi0bwcqnZRLkxxQUip7SNsJsVyN0Y1Y3uq02jTlennXzZv6
rFoWL2orZOdIqslHvzBv4T6oE4z6oK1ahRgBAhi7zLgfmXTqzmW8SX+DMxILP/Zi
51QPYe7giOYXtlsmsQwWqyqPPxXfN8P+CFogZqcRTu30DtAYmX9MT+uDu82ojPdK
+k8rT3L6iEGkOkV6PeIEcImlsk1vjgIN8cQCO+Meas/rD9weEmoYDc0KAPAqw6JQ
SyztEfy49r2/iQ9VjdKBDwx+dQ7lHrS+W1FJ8E2vyN4R6ngLMvzM0NYYzZu/9v7E
c7bczvtRJ3/mQ4mQJ7PQEHrNolSBqek577mMD8ZntZfyvdmw5TGt8isW5Mw0xtxy
5WyIxm2xNenKjCfda+pvqVec2qVuj2Ds2KakQ/yc1nwnUkjI45c1+llv/dr6MItB
WE9fDW3F4bbFdFZF9A/qJ4vJUnGBTzSpWfRV1YshPAsDY0HB1WsQexCxHzEZxEbW
6fJ0L36VY/2ryglgkVNPDeOnswnx2QIDAQABAoICABFNlmTxfABbdBlAW75MhAYE
C9tfKXcF1QywCfc7Q/HiJXZETPD8NiwMsyYlU/kx3cl0Kn9yG/ILSncb0RQ1a8sH
+ll1nnHZzI3NDzgQlKEh6llFOSPSWnuFrBbyvJTARdSVysgu+RmxjJ8JsH9StXg+
tI7mCFp9ns321Ipc/eqoJca9VlGBHkwBEfTp7cY6e0jXUnuVURfIe/4vIfSVdcHS
0gf7R93ihm2qXcuCgifhYi+dWXXijY2PhwP9oZilGmcRyYjZ7BBa46AhGLuTp4eB
hTLolwN7Dn5fb4bDXlQV2qjcexIvqtSb7Ny7shXP1j2x494uT3yinPF/Z3VGn5JR
9RmTshdA8fajTL1erPledECLEcrHzEg3rI5zJPIQbc56PAObVUOfV/wbCqtBbLNI
b4Q+JTFs+756fGyXxYGQl16UZ1XJ4renVuIZiNKEetPLPFiXTQ6EOpEhZRWE00J9
CzDD7p1NLvkaBVz31skm1g/ztZMDDuH/+FvRC3A9HQKWqCa5Eq7i3A/fYKzyI9gw
cgFFZQ47jKph7SUDJbES8jcyY6vvPR9kcXKTsnbuhKCduLOseT9FA+Sqf4k2PqTZ
GkSAUDKkpO+tvduJrlZ50x+C6FFzjLj0i+cxJJzw/nJlLz7hFUS5B3DrBqAtgL+7
PocgiEMblGSAbo6Exv65AoIBAQDsy2aBBewM8ym8vT9rZ3OH67AhOdRQb1cxQjkj
Tpn0vfF+DRv6ZGhHmWbVR5/40DD6cVA9qOOrrXwE2bePYk/e2Eo3hgzv1DLh7rK0
4ERNflT2Xa+Nrtdd94/4cdiPtSq2lplLhQlDn0Ow7mAwHiNjPGLjFO++q8DZ3Fva
fcpo15Y5lL30eQvWSHsvjrm8tk72V9tvDZ46JY6J/8epobRpBK0P5LkEKHSFO1tH
hsNb2JDWwkH+hVlZEPqY8CTznYFgBjclmgI9j4zZYdsbaEjy3tBoIabW2zcu+U8e
RzMK0mv/rYGh3wsRqVJT1GGFLaoAGEdYFqbBAHObt/xrgQa9AoIBAQDJD3DZJj2v
O+nI4Td3xljq1ZsJDsXAquHS49zi/BgjIsgS6M7r6YilfWu8sN8C4c+rES/u6UPs
jLOqFEA+sq14artQHK4T3wEr71UdlMB7LMwHjkVzqj63gV1Vft/vOBJ8WDXkqvw+
8asVyIy3Tt3XMpG+IYwFc93CVpAXOFPfvVXZ2ZHMGKKmmodHVyawLCDt7FahZxgP
fjjzMgHkgqhieEnrRjLAp9ECDmTWlyvMvl3Vt5M253jRzYt7CKrRNSGbcTfQ9nTs
3i+jyhw/0OQ3kuZQvGVRWOFetrwjvDp2ELj8YO/JDeIDiIyF2L+CfzftmBVdbCOO
5BPxgcKb1sdNAoIBAQDki7TVlver0A5aonXRnjm92FdY2k33jF8lpfsr/rNNqv6o
YNK+K6cSZBcCh2z5Y0fCkReXS6jijEEFFXW7qHHabfvD91gJKlAqDI7jUQnbmbE7
UFUedMBda5HDg2431e3x6Qzv/OliIRfeb1TbXFtfbmsrLYvwBinOnIbzLTHtWxcd
YFiu2x33pmFvF1xhrbwsu8OJPiWXjaQzwXHeYbqVGfRHQMTqJHnCFfYV5RYtUasJ
/NhhZidEdcTJVA72KvEx0w3q9uhurlyNe4tUuqSd9TxFJSW4fkCWz/3zBVlYepvO
XJKfv30ZgMl7K6MsPVS1XrmNZd9wrJTomP3CbPgpAoIBAQCdm1H9lqFx9MgtJIZj
iIL5CppuPjs77Xf55Y6oC68sE768O+zANx9bgnZqwkb+rl4ond9yKz6Idj78CsXV
oCClLR1KDkFS6FO1yfVxq8I6jAIfxiGhKonhNTIhq8QEdHLhMBCHAJWdDbnr6HqN
0u/JGiXu4cMuHwZtqYdn/EqbL4LVs1w7nfAaIzX58VItdVoWx1WdTgApXOttj/y1
0MoH7n0bRbrRFHudXgUjxfqak3tg5Xcr6cTmyXYV6tRkDH8cp2J2lktPxleXz/3W
9HuBKNEL5rKRUtfPc/UFGi7FkBRCGga9FvndhTOKVD7DH9CKmdXdlsBE6XrMrMgN
ew5dAoIBAETkPKDkf3HGLGq3JylyLUL9FNoabYbgtF6nXtvO2nzgt9qauNDL/W7Q
njbgvY3LsmGsxnR3df9U2Jk6DJuLp6gGfCEMYtxO1Lp05JLx0M37dP+gv16jkXS5
5ArWmI6QHK4XBMz/mAme6Yndrmqt3LV0IVu9PNJ3oGqVM+9ullkSFiG3Efq1ywEH
YN2aaoofMuzK9gOhb+SnMdFV31olfNW1jOGgPBNrRLMnAxd34TSkMqg/ztHJhU6A
zNJmhhmlFKN9pE3ejVI+oj4cYPNgpx3+lQl+TXPK47fq2nV0NXnKS6PXSTWQi2Nn
4w+JE3DLFSe6k9qUx1sOfYDBUjwLO9M=
-----END PRIVATE KEY-----
'''
