import { VerticalBox, HorizontalBox, Button, ScrollView, ListView, StandardButton, Palette} from "std-widgets.slint";

export component AppWindow inherits Window {
    in property <string> window_title: "";
    in-out property <string> error_message: "";

    in property <[string]> label_menu: ["Add profile", "Profiles"];
    in property <[string]> label_connect: ["Manual", "From file"];
    in property <[string]> labels_connect_manual: [
        "Address:",
        "Port:",
        "Root certificate:",
        "Certificate:",
        "Key:",
    ];
    in property <[string]> labels_profiles: [];
    in property <[string]> paths_profiles: [];

    out property <bool> opened_menu: false;
    in-out property <string> status_connect: "Disconnected";
    out property <int> selection_menu: 0;
    out property <int> selection_add_profile: 0;

    out property <[string]> selection_manual: ["", "", "", "", ""];
    out property <string> selection_from_file: "";

    callback ok_clicked();
    callback open_file() -> string;
    callback connect();
    callback disconnect();

    preferred-width: 1280px;
    preferred-height: 720px;
    min-width: 640px;
    min-height: 360px;
    title: window_title;

    TouchArea {
        visible: error_message != "";
        z: 100;
    }

    Rectangle {
        opacity: error_message != "" ? 1 : 0;
        animate opacity {
            duration: 200ms;
            easing: ease-in-out;
        }

        width: 320px;
        height: 180px;
        z: 101;
        border-width: 1px;
        border-color: Palette.foreground.with_alpha(0.6);
        VerticalBox {
            ScrollView {
                VerticalBox {
                    text_error := Text {
                        horizontal-stretch: 1;
                        text: error_message;
                        font-size: 15px;
                        wrap: char-wrap;
                    }
                }
            }

            batton := StandardButton {
                kind: ok;
                clicked => {
                    error_message = "";
                    ok_clicked();
                }
            }
        }
    }

    Rectangle {
        z: 99;
        background: error_message != "" ? #00000077 : #00000000;
        animate background {
            duration: 200ms;
            easing: ease-in-out;
        }
    }

    TouchArea {
        z: 99;
        visible: error_message != "";
    }

    Rectangle {
        y: 0px;
        height: 50px;
        z: 3;

        Text {
            x: 8px;
            y: -19px;
            font-size: 55px;
            text: "\u{2261}";
            color: Palette.foreground;
            opacity: area_menu.pressed ? 0.3 : 1.0;
        }

        area_menu := TouchArea {
            x: 0;
            width: parent.height;

            clicked => {
                opened_menu = !opened_menu;
            }
        }
    }

    Rectangle {
        y: 0px;
        height: 50px;

        Text {
            x: 55px;
            y: 3px;
            font-size: 30px;
            text: label_menu[selection_menu];
            color: Palette.foreground;
        }

        HorizontalLayout {
            y: 3px;
            padding-right: 10pt;
            alignment: end;
            Text {
                font-size: 30px;
                text: "Opaque VPN";
                color: Palette.foreground;
            }
        }
    }

    Rectangle {
        y: 49px;
        width: root.width;
        height: 2px;
        background: Palette.foreground;
    }

    Rectangle {
        z: 1;
        background: opened_menu ? #00000077 : #00000000;
        animate background {
            duration: 200ms;
            easing: ease-in-out;
        }
    }

    Rectangle {
        visible: opened_menu;
        z: 1;

        TouchArea {
            x: 0px;
            width: 260px;
        }

        TouchArea {
            x: 260px;
            width: parent.width - self.x;
            clicked => {
                opened_menu = false;
            }
        }
    }

    Rectangle {
        x: opened_menu ? 0px : -self.width;
        width: 260px;
        animate x {
            duration: 200ms;
            easing: ease-in-out;
        }
        z: 2;

        Rectangle {
            background: Palette.background;
        }

        Rectangle {
            background: #888;
            opacity: 0.1;
        }

        Text {
            x: 55px;
            y: 3px;
            font-size: 30px;
            text: "Menu";
            color: Palette.foreground;
        }

        Rectangle {
            y: 49px;
            height: 2px;
            background: Palette.foreground;
        }

        VerticalLayout {
            y: 50px;
            padding-top: 5px;
            spacing: 5px;

            for label[i] in label_menu: Rectangle {
                height: 30px;
                Text {
                    horizontal-alignment: center;
                    font-size: 20px;
                    text: label;
                    color: Palette.foreground;
                    opacity: area_list_menu.pressed ? 0.3 : 1.0;
                }

                Rectangle {
                    background: Palette.foreground;
                    opacity: area_list_menu.has-hover ? 0.1 : 0.0;
                }

                area_list_menu := TouchArea {
                    clicked => {
                        if (i != 0 || selection_menu != 0) {
                            selection_add_profile = 0;
                            selection_from_file = "";
                            input_add_profile_from_file.text = selection_from_file;
                        }
                        opened_menu = false;
                        selection_menu = i;
                    }
                }
            }
        }
    }

    Rectangle {
        y: - parent.height * 1.5 * selection_menu;
        animate y {
            duration: 200ms;
            easing: ease-in-out;
        }
        HorizontalLayout {
            y: 50px;
            height: 30px;

            for label[i] in label_connect: Rectangle {
                Text {
                    horizontal-alignment: center;
                    font-size: 20px;
                    text: label;
                    color: Palette.foreground;
                    opacity: area_list_add_profile.pressed ? 0.3 : 1.0;
                }

                Rectangle {
                    background: Palette.foreground;
                    opacity: area_list_add_profile.has-hover ? 0.1 : 0.0;
                }

                area_list_add_profile := TouchArea {
                    clicked => {
                        if (i == 0) {
                            selection_from_file = "";
                            input_add_profile_from_file.text = selection_from_file;
                        }
                        selection_add_profile = i;
                    }
                }
            }
        }

        Rectangle {
            x: selection_add_profile == 0 ? 0px : -self.width * 1.5;
            animate x {
                duration: 200ms;
                easing: ease-in-out;
            }

            ListView {
                x: 12px;
                y: 90px;
                width: parent.width - self.x;
                height: parent.height - self.y - button_connect.height;

                for label[i] in labels_connect_manual: HorizontalBox {
                    Text {
                        width: self.preferred-width;
                        font-size: 15px;
                        text: label;
                        horizontal-alignment: left;
                        color: Palette.foreground;
                    }

                    Rectangle {
                        height: input_add_profile_manual.preferred-height + 8px;
                        horizontal-stretch: 1;
                        background: input_add_profile_manual.has-focus ? Palette.foreground.with_alpha(0.2) : Palette.foreground.with_alpha(0.1);
                        border-width: input_add_profile_manual.has-focus ? 1px : 0px;
                        border-color: Palette.foreground.with_alpha(0.6);
                        input_add_profile_manual := TextInput {
                            x: 5px;
                            y: 4px;
                            width: parent.width - self.x * 2;
                            font-size: 15px;
                            horizontal-alignment: left;
                            wrap: char-wrap;

                            edited => {
                                selection_manual[i] = self.text;
                            }
                        }
                    }

                    Rectangle {
                        height: 29px;
                        width: self.height;

                        Text {
                            x: 5px;
                            y: -7px;
                            horizontal-alignment: center;
                            font-size: 30px;
                            text: "\u{2BBE}";
                            color: Palette.foreground;
                            opacity: area_add_profile_manual.pressed ? 0.3 : 1.0;
                        }

                        Rectangle {
                            background: Palette.foreground;
                            opacity: area_add_profile_manual.has-hover ? 0.1 : 0.0;
                        }

                        area_add_profile_manual := TouchArea {
                            clicked => {
                                selection_manual[i] = "";
                                input_add_profile_manual.text = selection_manual[i];
                                input_add_profile_manual.focus();
                            }
                        }
                    }
                }
            }
        }

        Rectangle {
            x: selection_add_profile == 1 ? 0px : self.width * 1.5;
            animate x {
                duration: 200ms;
                easing: ease-in-out;
            }
            HorizontalBox {
                padding-left: 18px;
                y: 90px;
                text_add_profile_from_file := Text {
                    font-size: 15px;
                    text: "File selected: ";
                    color: Palette.foreground;
                }

                view_add_profile_from_file := ScrollView {
                    height: parent.height - button_connect.height;

                    HorizontalLayout {
                        Rectangle {
                            height: input_add_profile_from_file.preferred-height + 8px;
                            horizontal-stretch: 1;
                            background: input_add_profile_from_file.has-focus ? Palette.foreground.with_alpha(0.2) : Palette.foreground.with_alpha(0.1);
                            border-width: input_add_profile_from_file.has-focus ? 1px : 0px;
                            border-color: Palette.foreground.with_alpha(0.6);
                            input_add_profile_from_file := TextInput {
                                x: 5px;
                                y: 4px;
                                width: parent.width - self.x * 2;
                                text: selection_from_file;
                                font-size: 15px;
                                horizontal-alignment: left;
                                wrap: char-wrap;

                                edited => {
                                    selection_from_file = self.text;
                                }
                            }
                        }

                        Rectangle {
                            y: -view_add_profile_from_file.viewport-y;
                            height: 29px;
                            width: self.height;

                            Text {
                                x: 5px;
                                y: -7px;
                                horizontal-alignment: center;
                                font-size: 30px;
                                text: "\u{2BBE}";
                                color: Palette.foreground;
                                opacity: area_add_profile_from_file.pressed ? 0.3 : 1.0;
                            }

                            Rectangle {
                                background: Palette.foreground;
                                opacity: area_add_profile_from_file.has-hover ? 0.1 : 0.0;
                            }

                            area_add_profile_from_file := TouchArea {
                                clicked => {
                                    selection_from_file = "";
                                    input_add_profile_from_file.text = selection_from_file;
                                    input_add_profile_from_file.focus();
                                }
                            }
                        }
                    }
                }
            }
        }
    }

    Rectangle {
        y: parent.height * 1.5 * (1 - selection_menu);
        animate y {
            duration: 200ms;
            easing: ease-in-out;
        }

        ListView {
            x: 12px;
            y: 60px;
            width: root.width - self.x;
            height: root.height - self.y;

            for label[i] in labels_profiles: Rectangle {
                height: 35px;
                HorizontalBox {
                    alignment: start;
                    Text {
                        font-size: 15px;
                        text: label;
                        color: Palette.foreground;
                        opacity: area_profiles_list.pressed ? 0.3 : 1.0;
                    }
                }

                Rectangle {
                    background: area_profiles_list.has-hover ? #ffffff18 : transparent;

                    area_profiles_list := TouchArea {
                        clicked => {
                            selection_from_file = paths_profiles[i];
                            connect();
                        }
                    }
                }
            }
        }
    }

    button_connect := Rectangle {
        height: 50px;
        y: root.height - self.height;
        background: #ff8b3d;

        Text {
            y: 3px;
            font-size: 30px;
            horizontal-alignment: center;

            text: selection_from_file == "" && selection_add_profile == 1 ? "Browse" : status_connect;
            color: Palette.foreground;
            opacity: area_add_profile_browse.pressed || (selection_menu == 1 && status_connect == "Disconnected") ? 0.3 : 1.0;
        }

        area_add_profile_browse := TouchArea {
            visible: selection_menu != 1 || status_connect != "Disconnected";
            clicked => {
                if (status_connect == "Disconnected") {
                    if (selection_from_file != "") {
                        connect();
                    } else if (selection_add_profile == 1) {
                        selection_from_file = open_file();
                        input_add_profile_from_file.text = selection_from_file;
                    }
                } else if (status_connect == "Connected") {
                    disconnect();
                }
            }
        }
    }
}
