import { VerticalBox,  ScrollView, StandardButton, Palette } from "std-widgets.slint";
import { Blur, LineEditInfo, TopPanel } from "utils.slint";
import { BottomButton } from "button.slint";
import { MenuScreen } from "screens/menu.slint";
import { AddProfileScreen } from "screens/add_profile.slint";
import { ProfilesScreen } from "screens/profiles.slint";
import { MessageScreen } from "screens/message.slint";

export global Status {
    in property <int> status: 0;
    out property <string> status_text:
        status == 0 ? "Disconnected" : status == 1 ? "Connected" : status == 2 ? "Disconnecting" : "Connecting";
    out property <string> button_text:
        status == 0 ? "Connect" : status == 1 ? "Disconnect" : status == 2 ? "Disconnecting..." : "Abort";
    out property <bool> is_disconnected: status == 0;
    out property <bool> is_connected: status == 1;
    out property <bool> is_disconnecting: status == 2;
    out property <bool> is_connecting: status == 3;

    public pure function conf_label(trigger: bool, label: string) -> string {
        return trigger && label != "" ? " to " + label : "";
    }
}

export component AppWindow inherits Window {
    in property <string> window_title;
    in property <bool> freeze;
    in property <[LineEditInfo]> profiles <=> profiles_screen.info;
    in-out property <string> message;
    in-out property <[LineEditInfo]> manual: [
        { label: "Address:", text: "" },
        { label: "Port:", text: "" },
        { label: "Root certificate:", text: "" },
        { label: "Certificate:", text: "" },
        { label: "Key:", text: "" },
    ];
    in-out property <LineEditInfo> from_file: { label: "", text: "" };
    out property <int> menu_index: 0;

    callback browse <=> add_profile_screen.browse;
    callback reload;
    callback disconnect();
    callback connect();

    preferred-width: 1280px;
    preferred-height: 720px;
    min-width: 640px;
    min-height: 360px;
    title: window_title;

    blur := Blur {
        z: 2;
        trigger: parent.freeze;
        freeze: true;
    }

    message_screen := MessageScreen {
        z: 10;
        text <=> parent.message;
    }

    top_panel := TopPanel {
        width: parent.width;
        text-left: menu_screen.section;
        text-right: Status.status_text + Status.conf_label(Status.is_connected, parent.from_file.label);
    }

    menu_screen := MenuScreen {
        z: 1;
        clicked(i) => {
            if (i != parent.menu_index) {
                parent.from_file = { label: "", text: "" };
                profiles_screen.selected = -1;
                add_profile_screen.selection = 0;
            }
            parent.menu_index = i;
        }
    }

    add_profile_screen := AddProfileScreen {
        y: top_panel.height - parent.height * 1.5 * (parent.menu_index - 0);
        height: parent.height - top_panel.height - bottom_button.height;
        manual_info <=> parent.manual;
        from_file_info <=> parent.from_file;
    }

    profiles_screen := ProfilesScreen {
        y: top_panel.height - parent.height * 1.5 * (parent.menu_index - 1);
        height: parent.height - top_panel.height - bottom_button.height;
        clicked(info) => {
            parent.from_file = info;
        }

        reload => {
            parent.reload();
            if (self.selected != -1 && self.selected < parent.profiles.length) {
                parent.from_file = profiles[self.selected];
            } else {
                parent.from_file = { label: "", text: "" };
                self.selected = -1;
            }
        }
    }

    bottom_button := BottomButton {
        touch_area-visible: parent.from_file.text != "" && !Status.is_disconnecting;
        y: parent.height - parent.y - self.height;
        text: Status.button_text + Status.conf_label(Status.is_disconnected, parent.from_file.label);
        background: #ff8b3d;
        clicked => {
            if (Status.is_disconnected) {
                parent.connect();
            } else if (!Status.is_disconnecting) {
                parent.disconnect();
            }
        }
    }
}
